Features/issue 38
andrekirst/04_KataFahrplanauskunft pull request #50
Opened 2017-02-10 13:41 UTC by slempart

Bitte mal gucken

2017-02-10 14:25 UTC, andrekirst commented
@slempart Es fehlt noch die Dokumentation für den Test der Logik. Zum Beispiel wie in Zeit_Konverter.md in /Dokumentation/Tests/Funktionen/Zeit_Konverter.md

2017-02-10 14:28 UTC, andrekirst requested changes

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft.Test/Funktionen/T_Logik.cs
> +        private List<Haltestelle> Lade_Test_Haltestellen()
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Funktionen/Logik.cs
> +    internal class Logik
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Funktionen/Logik.cs
> +        internal static List<Umstiegspunkt> Liefere_eindeutige_Umsteigepunkte(List<Umstiegspunkt> umstiegspunkte)
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Funktionen/Logik.cs
> +        internal static List<Umstiegspunkt> Liefere_Umsteigepunkte_fuer_Linie(Linie linie, List<Haltestelle> haltestellen)
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Funktionen/Logik.cs
> +        internal static List<Haltestelle> Liefere_Haltestellen_einer_Linie(string linien_name, List<Haltestelle> haltestellen)
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Funktionen/Logik.cs
> +        internal static List<Haltestelle> Liefere_Haltestellen_einer_Linie(Linie linie, List<Haltestelle> haltestellen)
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Objekte/Umstiegspunkt.cs
> +    public class Umstiegspunkt
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Objekte/Umstiegspunkt.cs
> +        public Umstiegspunkt()
Kommentar hinzufügen

2017-02-10 14:28 UTC, andrekirst commented on src/Fahrplanauskunft/Fahrplanauskunft/Objekte/Umstiegspunkt.cs
> +        public Umstiegspunkt(Haltestelle haltestelle)
Kommentar hinzufügen

2017-02-19 18:21 UTC, slempart commented
Doku Logik.dm hinzugefügt

2017-02-20 15:43 UTC, andrekirst approved these changes
Sieht gut aus.

2017-02-20 15:44 UTC, merged