Pull request für #62 - Guildeine für Branching erstellen
andrekirst/04_KataFahrplanauskunft pull request #64
Opened 2017-03-12 18:28 UTC by andrekirst

Bitte einmal gucken, ob das so passt.

2017-03-13 15:15 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +  * [Anleitung für das erstellen eines neuen Feature-Branch](branching_guide.md/#anleitung-f%C3%BCr-das-erstellen-eines-neuen-feature-branch)
Rechtschreibung: Erstellen

2017-03-13 15:20 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +
Rechtschreibung: Erstellen bzw. Reviewen

2017-03-13 15:21 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +[*Offizielle Hilfe für das mergen eines Pull request in GitHub*](https://help.github.com/articles/merging-a-pull-request/)
Rechtschreibung: Mergen

2017-03-13 15:23 UTC, slempart commented on CONTRIBUTING.md
> +Es wurde eine [Guideline](Dokumentation/Projekt/branching_guide.md) erstellt, um zu verstehen, wie in diesem Projekt Branches angelegt und gemerged werden, sowie Pull requests angelegt und abgeschlos
Rechtschreibung: gemergt

2017-03-13 15:25 UTC, slempart commented on CONTRIBUTING.md
> +1. Branch erstellen. Siehe [*Anleitung für das erstellen eines neuen Feature-Branch*](Dokumentation/Projekt/branching_guide.md/#anleitung-f%C3%BCr-das-erstellen-eines-neuen-feature-branch)
Rechtschreibung: Erstellen

2017-03-13 15:29 UTC, slempart requested changes
Bitte korrigieren

2017-03-13 20:25 UTC, andrekirst commented on Dokumentation/Projekt/branching_guide.md
> +  * [Anleitung für das erstellen eines neuen Feature-Branch](branching_guide.md/#anleitung-f%C3%BCr-das-erstellen-eines-neuen-feature-branch)
Behoben und einen neuen Stand eingecheckt

2017-03-13 20:25 UTC, andrekirst commented on Dokumentation/Projekt/branching_guide.md
> +
Behoben und einen neuen Stand eingecheckt

2017-03-13 20:26 UTC, andrekirst commented on Dokumentation/Projekt/branching_guide.md
> +[*Offizielle Hilfe für das mergen eines Pull request in GitHub*](https://help.github.com/articles/merging-a-pull-request/)
Behoben und einen neuen Stand eingecheckt

2017-03-13 20:26 UTC, andrekirst commented on CONTRIBUTING.md
> +Es wurde eine [Guideline](Dokumentation/Projekt/branching_guide.md) erstellt, um zu verstehen, wie in diesem Projekt Branches angelegt und gemerged werden, sowie Pull requests angelegt und abgeschlos
Behoben und einen neuen Stand eingecheckt

2017-03-13 20:26 UTC, andrekirst commented on CONTRIBUTING.md
> +1. Branch erstellen. Siehe [*Anleitung für das erstellen eines neuen Feature-Branch*](Dokumentation/Projekt/branching_guide.md/#anleitung-f%C3%BCr-das-erstellen-eines-neuen-feature-branch)
Behoben und einen neuen Stand eingecheckt

2017-03-14 22:18 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +  * [Anleitung für das aktualisieren von **develop** in einen Feature-Branch](branching_guide.md/#anleitung-f%C3%BCr-das-aktualisieren-von-develop-in-einen-feature-branch)
Rechtschreibung:  Aktualisieren

2017-03-14 22:21 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +**Wichtig**: Es wird **niemals** direkt auf diesem Branch ein Commit erstellt. Nur über Pull requests, wird Code diesem Branch hinzugefügt.
Rechstschreibung: kein Komma

2017-03-14 22:22 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +**Wichtig**: Es wird **niemals** direkt auf diesem Branch ein Commit erstellt. Nur über Pull requests, wird Code diesem Branch hinzugefügt.
Rechtschreibung: kein Komma

2017-03-14 22:28 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +Der Kommentar beinhaltet am anfang ein #, gefolgt der Issue-Number, einem Leerzeichen, Bindestrich, Leerzeichen und einem kurzen Kommentar.
Rechtschreibung: Anfang; gefolgt von der Issue-Nummer, einem Bindestrich, einem Leerzeichen....

2017-03-14 22:32 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +1. `git branch features/issue_<Nummer des Issue>`
Rechtschreibung: ...des Issues>... **4x**

2017-03-14 22:39 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +### Anleitung für das aktualisieren von **develop** in einen Feature-Branch
Rechtschreibung: Aktualisieren

2017-03-14 22:41 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +1. Auswählen des Reiters [*Pull requrst*](https://github.com/andrekirst/04_KataFahrplanauskunft/pulls)
Rechtschreibung: request

2017-03-14 22:42 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +1. Auswahlen des *base* (Standardmäßig **develop**), in dem die Änderungen eingespielt werden sollen
Rechtschreibung: Auswählen

2017-03-14 22:43 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +1. Klick auf *Create pull request* führt dazu, dass weitere Informationen zum pull request angegeben werden können
Rechtschreibung: zum Pull...

2017-03-14 22:49 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +1. Bei *Labels* ein *Label* zuordnen. Hier werden die Labels zugeordnet, dem auch dem Issue zugeordnet sind
Rechtschreibung: ...dem auch der Issue zugeordnet ist

2017-03-14 22:51 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +**Information**: Solange der Pull request offen ist, können immer wieder neue Commits in den Branch, aus dem der Pull request entstanden ist, hochgeladen werden. Der letzte Commit löst das Ereignis a
Rechtschreibung: ...aus, das z.B. ... neu erstellt.

2017-03-14 22:53 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +1. Klick auf *Confirm squash and merge*, um den Pull request-Vorgang abuischließen
Rechtschreibung: ...abzuschließen

2017-03-14 22:56 UTC, slempart requested changes
Bitte korrigieren

2017-03-15 06:18 UTC, andrekirst commented on Dokumentation/Projekt/branching_guide.md
> +1. Bei *Labels* ein *Label* zuordnen. Hier werden die Labels zugeordnet, dem auch dem Issue zugeordnet sind
Ich habe es folgendermaßen geändert: "Bei *Labels* vorhandene Labels zuordnen. Hier werden die Labels zugeordnet, dem auch dem Issue zugeordnet sind"
Nur das mit ", dem auch dem..." - klingt irgendwie komisch

2017-03-15 06:21 UTC, andrekirst commented
@slempart Ich habe Korrekturen vorgenommen

2017-03-15 20:58 UTC, slempart commented on Dokumentation/Projekt/branching_guide.md
> +1. Klick auf *Squash and merge* - Dies beduetet, dass alle Commits in einen Commit zusammengefasst werden und auf den *base*, z.B. **develop**, gesetzt wird
Rechtschreibung: bedeutet

2017-03-15 20:59 UTC, slempart requested changes
Leider noch mal gucken

2017-03-16 06:29 UTC, andrekirst commented on Dokumentation/Projekt/branching_guide.md
> +1. Klick auf *Squash and merge* - Dies beduetet, dass alle Commits in einen Commit zusammengefasst werden und auf den *base*, z.B. **develop**, gesetzt wird
Ich habe den Satz nochmal umformuliert, weil ich die einstellung so geändert habe, dass wir jetzt nur Merge Commits machen.

2017-03-16 15:06 UTC, slempart approved these changes
Fertig

2017-03-16 15:07 UTC, merged